apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opsagent.fullname" . }}
  labels:
    {{- include "opsagent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "opsagent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "opsagent.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: GROQ_API_KEY
              value: {{ .Values.env.groqApiKey | quote }}
            - name: SLACK_WEBHOOK_URL
              value: {{ .Values.env.slackWebhookUrl | quote }}
            - name: AUTO_HEAL_ENABLED
              value: {{ .Values.env.autoHealEnabled | quote }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
